### CREATE A PRODUCT:
POST http://localhost:3000/products
X-Tenant-ID: acme
Authorization: Bearer <jwt-token>
Content-Type: application/json

{
  "name": "Laptop Pro 15",
  "description": "High-performance laptop",
  "price": 1299.99,
  "stock": 50
}


### GET ALL PRODUCTS:
GET http://localhost:3000/products
X-Tenant-ID: acme
Authorization: Bearer <jwt-token>


### GET A PRODUCT BY ID:
GET http://localhost:3000/products/{product-id}
X-Tenant-ID: acme
Authorization: Bearer <jwt-token>


### GET PRODUCT STATISTICS:
GET http://localhost:3000/products/stats
X-Tenant-ID: acme
Authorization: Bearer <jwt-token>


### UPDATE A PRODUCT:
PUT http://localhost:3000/products/{product-id}
X-Tenant-ID: acme
Authorization: Bearer <jwt-token>
Content-Type: application/json

{
  "price": 1199.99,
  "stock": 45
}


### DELETE A PRODUCT:
DELETE http://localhost:3000/products/{product-id}
X-Tenant-ID: acme
Authorization: Bearer <jwt-token>

