### CREATE A NEW TENANT
POST http://localhost:3000/tenants
Content-Type: application/json

{
  "name": "Acme Corporation",
  "subdomain": "acme"
}

### GET ALL TENANTS
GET http://localhost:3000/tenants

### GET A TENANT BY ID
GET http://localhost:3000/tenants/7566502f-082a-44e1-b95b-3e08cfa5b68b

### UPDATE A TENANT
PUT http://localhost:3000/tenants/1
Content-Type: application/json

{
  "name": "Acme Corporation",
  "subdomain": "acme"
}

### DELETE A TENANT
DELETE http://localhost:3000/tenants/7566502f-082a-44e1-b95b-3e08cfa5b68b